---
apiVersion: v1
kind: Service
metadata:
  name: jenkins
  namespace: jenkins
  labels:
    app: jenkins
    project: jenkins
spec:
  ports:
    - name: http-port
      port: 8080
      targetPort: 8080
      nodePort: 30000
    - name: jnlp-port
      port: 50000
      targetPort: 50000
      nodePort: 30001
  selector:
    app: jenkins
    tier: jenkins
    project: jenkins
  type: NodePort